export DJANGO_ENV="development"
export POSTGRES_USER="postgres"
export POSTGRES_DB="wf_development"
export POSTGRES_PASSWORD="EI6dbPfDn6jCBnOn"
export POSTGRES_HOST="35.222.109.219"
export POSTGRES_PORT="5432"
