apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-interface-vs
spec:
  hosts:
  - "*"
  gateways:
  - istio-gateway
  http:
  - route:
    - destination:
        host: user-interface-svc
        port:
          number: 3000