apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "weather-forecast-backend"
spec:
  rules:
  - http:
      paths:
      - path: /manager/*
        backend:
          serviceName: "manager-svc"
          servicePort: 8000
      - path: /session_manager/*
        backend:
          serviceName: "session-manager-svc"
          servicePort: 8100
      - path: /weather_data_retrieval/*
        backend:
          serviceName: "data-retrieval-svc"
          servicePort: 8200
      - path: /model_execution/*
        backend:
          serviceName: "model-execution-svc"
          servicePort: 8300
