# Generated by Django 2.2.5 on 2020-02-08 02:01

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ascii_name', models.CharField(max_length=200, null=True)),
                ('alternate_names', models.CharField(max_length=5000, null=True)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('feature_class', models.CharField(max_length=100, null=True)),
                ('feature_code', models.CharField(max_length=100, null=True)),
                ('country_code', models.CharField(max_length=100, null=True)),
                ('alternate_country_code', models.CharField(max_length=100, null=True)),
                ('admin_code_1', models.CharField(max_length=100, null=True)),
                ('admin_code_2', models.CharField(max_length=100, null=True)),
                ('admin_code_3', models.CharField(max_length=100, null=True)),
                ('admin_code_4', models.CharField(max_length=100, null=True)),
                ('population', models.IntegerField()),
                ('elevation', models.CharField(max_length=100, null=True)),
                ('timezone', models.CharField(max_length=100)),
                ('modification_date', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('visible_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('geo_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('alternate_names', models.CharField(max_length=5000, null=True)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=35, null=True)),
                ('admin_code', models.CharField(max_length=100, null=True)),
                ('population', models.IntegerField()),
                ('elevation', models.CharField(max_length=100, null=True)),
                ('timezone', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
    ]
